# tensors

**Ps:建议学完numpy再学习pytorch**

使用的数据集是FashionMNIST

Tensors是一个和**数组**和**矩阵**类似的基本数据结构。我们可以在pytorch中使用tensors去编码Model的input data、output data以及model's parameters。

Tensors和Numpy中的ndarrays类似，不过tensors还可以运行在GPU以及其它的硬件上。事实上，Tensors与Numpy的array除了复制数据以外，往往是共享**同样的底层memory**。Tensors有针对automatic differentiation的优化。

In [1]:
import torch
import numpy as np

## 1. 初始化一个Tensor

Tensors可以通过各种各样的方式进行初始化。

### 1.1 通过Python List进行初始化

In [2]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)

### 1.2 通过Numpy的array进行初始化

In [3]:
np_array=np.array(data)
x_np = torch.from_numpy(np_array)

### 1.3 通过另外一个tensor进行初始化

In [5]:
x_ones = torch.ones_like(x_data) # 只保留x_data的属性包括shape和datatype
print(f"Ones Tensor:\n{x_ones}\n")

x_rand =torch.rand_like(x_data,dtype=torch.float) # 保留shape改变datatype
print(f"Random Tensor:\n {x_rand}\n")


Ones Tensor:
tensor([[1, 1],
        [1, 1]])

Random Tensor:
 tensor([[0.2708, 0.9801],
        [0.7570, 0.4160]])



### 1.4 使用torch初始化Tensor 

In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9400, 0.2946, 0.6954],
        [0.5766, 0.7224, 0.8638]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 2.Tensor的属性

In [8]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 3. Tensor 运算

pytorch提供了超过100种Tensor的运算，包括算术运算，线性代数，矩阵运算，取样等等。详见
[这里](https://pytorch.org/docs/stable/torch.html)

这些运行在GPU上，如果你使用colab，分配一个GPU，速度上Runtime>Change runtime type>GPU。

默认的tensors会在CPU上创建，我们需要明确的将tensors将tensors使用.to的方法使用GPU，在此之前先检查GPU加速是否可用。**注意，在设备上复制大型tensors在时间和存储方面上需要付出很大代价！**

In [9]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

### 3.1 类似于numpy的索引和切片操作

In [10]:
tensor = torch.ones(4,4)
print('First row:',tensor[0])
print('First column:',tensor[:,0])
print('Last column:',tensor[...,-1])
tensor[:,1]=0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### 3.2 tensors的连接
使用torch.cat方法和torch.stack方法，这两个方法有微小的差异，可以连接不同的tensors。



In [11]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


### 3.3 算数运算

In [12]:
# 计算两个tensor的矩阵乘积. y1, y2, y3有相同的结果
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# 计算两个矩阵对应位置元素进行乘积(element-wise product). z1, z2, z3 有相同的结果
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### 3.4 单元素的tensors
如果tensor中只有一个元素，可以通过item方法将tensor转为一个Python的数值类型。

In [13]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


### 3.5 In-place operations 
该操作不经过复制操作，而是直接在原来的内存上改变它的值叫做in-place. 经常加后缀“_”来代表in-place operation. 例如 x.copy_(y), x.t_(), 将会改变 x。

In [14]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


注意：In-place operations保存了一些内存的空间，但是当在计算derivatives时往往会出现问题，因为会立即失去之前的值。因此不建议使用。

## 4 Numpy桥

Tensors在CPU上和Numpy共享一样的内存位置，如果改变了其中一个，另一个也会被改变。

### 4.1 tensor转numpy

In [15]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


tensor的改变将会影响到Numpy的array

In [16]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### 4.2 numpy转tensor

In [17]:
n = np.ones(5)
t = torch.from_numpy(n)

Numpy的array的值改变将会影响到tensor

In [18]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
